### ISSUE TITLE
API

### ISSUE THREAD

**Issue by stropitek** [cheminfo-js/equilibrium2#5]
There is a fondamental problem with how the main function that calculates an equilibrium works. It takes an input and modifies that input. Instead the input should not be modified and the function should return an output with the concentrations at equilibrium.

I think the input structure could be simplified. In `components`, you could remove the flag `fixesEquilibriumQuantity` and instead consider the quantity at equilibrium should be fixed when `atEquilibrium` is defined.

What is `volume`? Is it used?

Current input structure: 

``` js
var equilibriumModel={
    volume:1,
    species: [
        {
            label:"Na+",
            charge:1,
            total:2.2,
            atEquilibrium: 0,
            fixesEquilibriumQuantity: false
        },
        {
            label:"CO3--",
            charge:-2,
            total:1,
            atEquilibrium: 0,
            fixesEquilibriumQuantity: false
        },
        {
            label:"H+",
            charge:1,
            total:-0.2,
            atEquilibrium: 0,
            fixesEquilibriumQuantity: false
        }
    ],
    components:[
        {
            label:"HCO3-",
            species: [0, 1, 0, 0, 1],
            constant:-6,
            atEquilibrium: 0,
            fixesEquilibriumQuantity: false
        },
        {
            label:"OH-",
            species: [0, 0, 0, 0, -1],
            constant:14,
            atEquilibrium: 0,
            fixesEquilibriumQuantity: false
        }
    ]
};
```

**Comment by minibrasiler** [comment]
I don’t understand why is it a problem to change the input…
Can I do a clone of it and change the value that I want?
The volume could be interesting if we want to know the number of mole that precipitate or to do a titration.

Le 13 mai 2016 à 16:35, Daniel Kostro <notifications@github.com<mailto:notifications@github.com>> a écrit :


There is a fondamental problem with how the main function that calculates an equilibrium works. It takes an input and modifies that input. Instead the input should not be modified and the function should return an output with the concentrations at equilibrium.

Current input structure:

var equilibriumModel={
    volume:1,
    species: [
        {
            label:"Na+",
            charge:1,
            total:2.2,
            atEquilibrium: 0,
            fixesEquilibriumQuantity: false
        },
        {
            label:"CO3--",
            charge:-2,
            total:1,
            atEquilibrium: 0,
            fixesEquilibriumQuantity: false
        },
        {
            label:"H+",
            charge:1,
            total:-0.2,
            atEquilibrium: 0,
            fixesEquilibriumQuantity: false
        }
    ],
    components:[
        {
            label:"HCO3-",
            species: [0, 1, 0, 0, 1],
            constant:-6,
            atEquilibrium: 0,
            fixesEquilibriumQuantity: false
        },
        {
            label:"OH-",
            species: [0, 0, 0, 0, -1],
            constant:14,
            atEquilibrium: 0,
            fixesEquilibriumQuantity: false
        }
    ]
};

I think the input structure could be simplified. In components, you could remove the flag fixesEquilibriumQuantity and instead consider the quantity at equilibrium should be fixed when atEquilibrium is defined.

What is volume? Is it used?
