### ISSUE TITLE
LU matrix is singular matrix error

### ISSUE THREAD

**Issue by stropitek** [cheminfo-js/equilibrium2#7]
The example with H2CO3 now seems to work well in the browser. I've tried other scenarios and I get a `LU matrix is singular` error when running a test case with  H3P04. 

I've added a file in `examples` that reproduces it

**Comment by targos** [comment]
If a matrix is singular, the LU decomposition cannot work

**Comment by stropitek** [comment]
Yes, I figured that out. I'm wondering if it's normal in this case that we end up with a Matrix that is not invertable. @minibrasiler you could have a look at this when you're done with your exams

**Comment by minibrasiler** [comment]
Thanks you Daniel for your message and for the work that you have done.
I just have a question, the script works with other example or just with the H2CO3?
I have already seen this message of error for the inverse Matrix, I think it's come from the fact that the number in the matrix are too big or too small... Maybe it is better to make our own function for the inverse matrix? I will see this after my exams.

Have a good day!


Envoy? de mon iPhone

Le 21 juin 2016 ? 13:09, Daniel Kostro <notifications@github.com<mailto:notifications@github.com>> a ?crit :


Yes, I figured that out. I'm wondering if it's normal in this case that we end up with a Matrix that is not invertable. @minibrasiler<https://github.com/minibrasiler> you could have a look at this when you're done with your exams

-

**Comment by stropitek** [comment]
I tried some combinations and I could reproduce in one case: H2S
I never seem to have the problem with species that dissociate only once
